name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run tests
        run: deno task test

  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno fmt --check
      - run: deno lint
